#!/usr/bin/env python3
"""One P4 capture: server cells, renderer cells, controls, and the CSV rows.

The performance protocol wants **two agreeing runs** and a **confirmation
retake** for anything that lands near its threshold, so this script is the unit
that gets repeated:

    python3 dev-docs/bench/scripts/capture.py --run 1
    python3 dev-docs/bench/scripts/capture.py --run 2

Each run records the machine state it was taken under (`R11` corollary — a
longitudinal number carries its conditions, and KGLite's 0.15.7 baseline was
captured hot with nothing saying so). It never *waits* for a quiet machine:
waiting costs more in stalled work than the precision it buys, and validity
comes from the controls, the two runs, and the retake.

**This is not part of `make gate`, deliberately.** Perf is never asserted in the
correctness gate (test-plan L4): a gate that goes red because the laptop was
busy is a gate people learn to bypass, and a timing threshold in a correctness
suite is a flake generator with a plausible cover story.

Heavy artifacts land in `bench/out/` (purged); the small numbers land in
`bench/results/results.csv` (never purged). Nothing is written next to this
script.
"""

from __future__ import annotations

import argparse
import csv
import json
import platform
import statistics
import subprocess
import sys
import time
import urllib.request
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
OUT = REPO / "dev-docs/bench/out"
RESULTS = REPO / "dev-docs/bench/results/results.csv"

# The three scale points: below the bound, at the bound, above it. Generated by
# the same `make fixture` machinery as the committed fixture, seeded, and
# regenerable — which is why they live in the purged tier.
GRAPHS = {
    "1k": OUT / "scale-1000.kgl",
    "5k": OUT / "scale-5000.kgl",
    "20k": OUT / "scale-20000.kgl",
}
# Renderer cells are driven against the largest graph: it is the only one whose
# `Person` type can fill a slice at the bound *and* report a truthful
# `total`, so the truncation metadata in the capture is real rather than
# incidentally absent.
RENDERER_GRAPH = GRAPHS["20k"]

COLUMNS = [
    "date",
    "run",
    "benchmark",
    "cell",
    "statistic",
    "value",
    "unit",
    "backend",
    "profile",
    "graph",
    "loadavg1",
    "power",
    "machine",
    "note",
]


def machine_state() -> dict[str, str]:
    """What the capture was taken under. Metadata, never a gate on taking it."""
    try:
        load1 = f"{__import__('os').getloadavg()[0]:.2f}"
    except OSError:
        load1 = "unknown"
    power = "unknown"
    try:
        batt = subprocess.run(
            ["pmset", "-g", "batt"], capture_output=True, text=True, timeout=10
        ).stdout
        if "AC Power" in batt:
            power = "ac"
        elif "Battery Power" in batt:
            power = "battery"
    except (OSError, subprocess.SubprocessError):
        pass
    machine = f"{platform.system()} {platform.release()} {platform.machine()}"
    return {"loadavg1": load1, "power": power, "machine": machine}


def run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    """Run a command and read ITS exit code, not something downstream of it."""
    print(f"  $ {' '.join(cmd)}", file=sys.stderr)
    proc = subprocess.run(cmd, cwd=REPO, text=True, **kw)
    if proc.returncode != 0:
        raise SystemExit(f"capture: FAIL — {cmd[0]} exited {proc.returncode}")
    return proc


def preconditions() -> str:
    """Release binary, production bundle, and the graphs. Refuse, don't warn."""
    run(["python3", "scripts/check_bundle.py", "--freshness"])
    binary = subprocess.run(
        ["python3", "scripts/check_bundle.py", "--resolve-binary", "kglite-visual"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    if "/release/" not in binary:
        raise SystemExit(
            f"capture: FAIL — resolved a non-release binary ({binary}). "
            "Debug-profile timings are not evidence (R11); run "
            "`cargo build --release -p kglite-visual-cli` first."
        )
    missing = [str(p) for p in GRAPHS.values() if not p.exists()]
    if missing:
        raise SystemExit(
            "capture: FAIL — scale fixtures missing: "
            + ", ".join(missing)
            + "\n  Generate them with, e.g.:\n"
            "  cargo run --release -p kglite-visual-core --example make_fixture "
            "-- --persons 20000 --out dev-docs/bench/out/scale-20000.kgl"
        )
    return binary


def server_cells(run_id: str, repeats: int) -> list[tuple[str, dict]]:
    """The server half, one JSON document per graph."""
    out = []
    for tag, path in GRAPHS.items():
        dest = OUT / f"server-{tag}-run{run_id}.json"
        proc = run(
            [
                "cargo",
                "run",
                "--release",
                "-q",
                "-p",
                "kglite-visual-core",
                "--example",
                "bench_server",
                "--",
                str(path.relative_to(REPO)),
                str(repeats),
            ],
            capture_output=True,
        )
        dest.write_text(proc.stdout)
        out.append((tag, json.loads(proc.stdout)))
    return out


def renderer_cells(run_id: str, backends: list[str], loads: int) -> list[tuple[str, dict]]:
    """The client half, one JSON document per backend."""
    out = []
    for backend in backends:
        dest = OUT / f"renderer-{backend}-run{run_id}.json"
        run(
            [
                "node",
                "dev-docs/bench/scripts/bench_renderer.mjs",
                "--graph",
                str(RENDERER_GRAPH.relative_to(REPO)),
                "--backend",
                backend,
                "--sizes",
                "1000,5000",
                "--synthetic",
                "1000,5000,20000",
                "--loads",
                str(loads),
                "--run",
                run_id,
                "--out",
                str(dest.relative_to(REPO)),
            ],
            stdout=subprocess.DEVNULL,
        )
        out.append((backend, json.loads(dest.read_text())))
    return out


@contextmanager
def serving(binary: str, graph: Path):
    """The release CLI over one graph, torn down on the way out.

    The launch contract is part of what this reads: exactly one JSON line on
    stdout with the resolved port. Scraping stderr or racing a fixed port is
    what this replaces.
    """
    proc = subprocess.Popen(
        [binary, str(graph.relative_to(REPO)), "--no-open", "--port", "0"],
        cwd=REPO,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    try:
        line = proc.stdout.readline()
        if not line:
            raise SystemExit(f"capture: FAIL — {binary} produced no stdout line")
        yield json.loads(line)
    finally:
        proc.kill()
        proc.wait(timeout=10)


def twin_cells(binary: str, graph: Path, repeats: int) -> dict:
    """The same expansion, measured a second way — through the JSON twin.

    §9: *measure an important claim two independent ways; a single measurement
    cannot detect its own instrument bug.* `bench_server` times a `Session` in
    process; this times the identical request arriving over HTTP at the running
    release binary. The two share no clock, no process and no code path beyond
    core itself, so agreement is evidence and disagreement is a finding.

    The number here is necessarily larger — it carries the socket, the JSON
    serialization and the reader — and that difference IS the transport cost,
    reported rather than subtracted.
    """
    out: dict = {}
    with serving(binary, graph) as info:
        base = info["url"].rstrip("/")

        def post(path: str, body: dict) -> tuple[float, bytes]:
            payload = json.dumps(body).encode()
            req = urllib.request.Request(
                f"{base}{path}", data=payload, headers={"content-type": "application/json"}
            )
            start = time.perf_counter()
            with urllib.request.urlopen(req, timeout=180) as resp:
                data = resp.read()
            return (time.perf_counter() - start) * 1000, data

        session = json.loads(urllib.request.urlopen(f"{base}/api/session", timeout=60).read())
        out["twin_max_expansion_nodes"] = {
            "statistic": "exact",
            "value": session["max_expansion_nodes"],
        }
        out["twin_max_query_rows"] = {"statistic": "exact", "value": session["max_query_rows"]}

        for limit in (1000, 5000):
            samples = []
            body_len = 0
            returned = 0
            for _ in range(repeats):
                # A fresh server per repeat would be honest but slow; instead the
                # slot space grows across repeats, which is exactly what a user
                # doing several expansions produces. The cell says so in its name.
                ms, data = post(
                    "/api/expand",
                    {
                        "slot": 0,
                        "relationship": "KNOWS",
                        "direction": "out",
                        "limit": limit,
                    },
                )
                samples.append(ms)
                body_len = len(data)
                returned = json.loads(data)["meta"]["bound"]["returned"]
            samples.sort()
            out[f"twin_expand_{limit}_roundtrip_ms"] = {
                "statistic": "median",
                "value": round(statistics.median(samples), 4),
                "p95": round(samples[min(len(samples) - 1, round((len(samples) - 1) * 0.95))], 4),
                "min": round(samples[0], 4),
                "max": round(samples[-1], 4),
                "n": len(samples),
            }
            out[f"twin_expand_{limit}_json_bytes"] = {"statistic": "exact", "value": body_len}
            out[f"twin_expand_{limit}_returned"] = {"statistic": "exact", "value": returned}
    return out


def unit_for(cell: str) -> str:
    if cell.endswith("_ms") or cell.endswith("_ms_first"):
        return "ms"
    if cell.endswith("_bytes"):
        return "bytes"
    if cell.endswith("_fps"):
        return "fps"
    return "count"


def rows_from_server(tag: str, doc: dict, state: dict, run_id: str, date: str) -> list[dict]:
    rows = []
    for cell, entry in doc.items():
        if not isinstance(entry, dict) or "statistic" not in entry:
            continue
        value = entry.get("value")
        if isinstance(value, str) and not value.replace(".", "", 1).isdigit():
            note = value
            value = ""
        else:
            note = ""
        extra = {k: v for k, v in entry.items() if k not in {"statistic", "value"}}
        rows.append(
            {
                "date": date,
                "run": run_id,
                "benchmark": "server",
                "cell": cell,
                "statistic": entry["statistic"],
                "value": value,
                "unit": unit_for(cell),
                "backend": "n/a",
                "profile": "release",
                "graph": tag,
                "note": note or (json.dumps(extra) if extra else ""),
                **state,
            }
        )
    return rows


def rows_from_renderer(backend: str, doc: dict, state: dict, run_id: str, date: str) -> list[dict]:
    rows = []
    for cell, entry in doc.items():
        if not isinstance(entry, dict) or "statistic" not in entry:
            continue
        # A frame-period cell carries a distribution, not one number: p95 is the
        # headline the stop rule reads, and the rest rides along in `note` so the
        # shape stays available (distribution shape is a diagnostic, not noise).
        if "p95" in entry:
            value = entry["p95"]
            note = json.dumps({k: entry[k] for k in entry if k not in {"statistic", "p95"}})
        else:
            value = entry.get("value")
            note = json.dumps({k: entry[k] for k in entry if k not in {"statistic", "value"}})
            if isinstance(value, (list, dict)):
                note = json.dumps(value)
                value = ""
            if note == "{}":
                note = ""
        rows.append(
            {
                "date": date,
                "run": run_id,
                "benchmark": "renderer",
                "cell": cell,
                "statistic": entry["statistic"],
                "value": value,
                "unit": unit_for(cell) if "p95" not in entry else "ms",
                "backend": backend,
                "profile": doc.get("profile", {}).get("value", "release"),
                "graph": "20k",
                "note": note,
                **state,
            }
        )
    return rows


def append(rows: list[dict]) -> None:
    RESULTS.parent.mkdir(parents=True, exist_ok=True)
    fresh = not RESULTS.exists()
    with RESULTS.open("a", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=COLUMNS, extrasaction="ignore")
        if fresh:
            writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--run", required=True, help="run identifier, e.g. 1 or 2 or 2-retake")
    ap.add_argument("--repeats", type=int, default=21, help="server-side repeats per cell")
    ap.add_argument("--loads", type=int, default=5, help="cold loads for time-to-first-paint")
    ap.add_argument(
        "--backends",
        default="gpu,swiftshader",
        help="gpu (headed, real Metal driver) and/or swiftshader (headless, CI shape)",
    )
    ap.add_argument("--skip-server", action="store_true")
    ap.add_argument("--skip-twin", action="store_true")
    ap.add_argument("--skip-renderer", action="store_true")
    args = ap.parse_args()

    binary = preconditions()
    state = machine_state()
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    print(f"capture run {args.run}: {binary}", file=sys.stderr)
    print(f"machine: {state}", file=sys.stderr)

    rows: list[dict] = []
    if not args.skip_server:
        for tag, doc in server_cells(args.run, args.repeats):
            rows += rows_from_server(tag, doc, state, args.run, date)
    if not args.skip_twin:
        # The second instrument, on the biggest graph: the same expansion, over
        # the wire, against the same release binary the renderer harness drives.
        # Independent of `--skip-server` on purpose — it is a separate
        # instrument, not a second view of the first one's output.
        twin = twin_cells(binary, RENDERER_GRAPH, min(args.repeats, 11))
        (OUT / f"twin-20k-run{args.run}.json").write_text(json.dumps(twin, indent=2) + "\n")
        rows += rows_from_server("20k", twin, state, args.run, date)
    if not args.skip_renderer:
        for backend, doc in renderer_cells(args.run, args.backends.split(","), args.loads):
            rows += rows_from_renderer(backend, doc, state, args.run, date)

    append(rows)
    print(f"capture run {args.run}: {len(rows)} rows -> {RESULTS}", file=sys.stderr)


if __name__ == "__main__":
    main()
