//! The protocol's two exact baselines (test-plan §L2), regenerated here and
//! diffed by the gate.
//!
//! 1. `frontend/src/generated/protocol-constants.ts` — the wire numbers the
//!    TypeScript decoder needs. ts-rs generates the message *shapes*; it has no
//!    concept of a constant, and a hand-written copy of `PROTOCOL_VERSION` on
//!    the client is exactly the drift the generated types exist to prevent.
//!    `make check-generated-ts` already guards that whole directory.
//! 2. `tests/baselines/framing.golden` — a byte-level dump of canonical frames.
//!    The TypeScript constants cannot catch a change to *layout* (a reordered
//!    header word keeps every constant), and that is the change that silently
//!    breaks an old client. `make check-protocol-baseline` guards it.
//!
//! **Both are exact baselines, so both fail the moment "make it pass" is
//! cheaper than "explain the diff"** (CLAUDE.md → "Gate honesty"). A red
//! baseline after a deliberate protocol change is a conscious decision:
//! regenerate in the same commit, bump `PROTOCOL_VERSION`, and say why.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use kglite_visual_core::protocol::{
    MessageType, ResponseEncoder, CHUNK_TARGET_BYTES, FLAG_TERMINAL, HEADER_BYTES, PROTOCOL_VERSION,
};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .canonicalize()
        .expect("the workspace root is two levels above this crate")
}

/// Write only when the content differs, so an unchanged run leaves the file's
/// mtime alone — the embedded-bundle freshness check compares mtimes, and a
/// baseline rewritten on every `cargo test` would keep marking sources newer
/// than the bundle built from them.
fn write_if_changed(path: &Path, content: &str) {
    if std::fs::read_to_string(path).ok().as_deref() == Some(content) {
        return;
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("baseline directory");
    }
    std::fs::write(path, content).expect("write baseline");
}

#[test]
fn generate_typescript_protocol_constants() {
    let mut out = String::new();
    out.push_str(
        "// Generated by crates/kglite-visual-core/tests/protocol_baseline.rs. \
         Do not edit this file manually.\n\
         // Regenerate with `cargo test -p kglite-visual-core`; \
         `make check-generated-ts` fails on drift.\n\n",
    );
    let _ = writeln!(out, "export const PROTOCOL_VERSION = {PROTOCOL_VERSION}");
    let _ = writeln!(out, "export const HEADER_BYTES = {HEADER_BYTES}");
    let _ = writeln!(out, "export const FLAG_TERMINAL = {FLAG_TERMINAL}");
    let _ = writeln!(
        out,
        "export const CHUNK_TARGET_BYTES = {CHUNK_TARGET_BYTES}"
    );
    out.push_str("\nexport const MessageType = {\n");
    for msg in MessageType::ALL {
        let _ = writeln!(out, "  {}: {},", msg.ts_name(), msg.code());
    }
    out.push_str("} as const\n\nexport type MessageTypeCode =\n  (typeof MessageType)[keyof typeof MessageType]\n");

    write_if_changed(
        &repo_root()
            .join("frontend/src/generated")
            .join("protocol-constants.ts"),
        &out,
    );
}

#[test]
fn generate_framing_golden() {
    // Canonical messages, chosen so the dump covers every framing rule: a
    // JSON payload that needs padding, an f32 array, an empty array, and a
    // terminal flag that lands on the last frame of a multi-frame response.
    let cases: Vec<(&str, Vec<Vec<u8>>)> = vec![
        ("session-info", {
            let mut enc = ResponseEncoder::new();
            enc.push_json(MessageType::SessionInfo, r#"{"protocol_version":1}"#);
            enc.finish()
        }),
        ("meta-graph", {
            let mut enc = ResponseEncoder::new();
            enc.push_json(MessageType::MetaGraphMeta, r#"{"tier":"full"}"#);
            enc.push_f32(MessageType::Points, &[0.0, 1.5, -2.25, 3.0]);
            enc.push_f32(MessageType::Links, &[0.0, 1.0]);
            enc.finish()
        }),
        ("empty-links", {
            let mut enc = ResponseEncoder::new();
            enc.push_f32(MessageType::Links, &[]);
            enc.finish()
        }),
        ("error", {
            let mut enc = ResponseEncoder::new();
            enc.push_json(MessageType::Error, r#"{"message":"nope"}"#);
            enc.finish()
        }),
    ];

    let mut out = String::new();
    out.push_str(
        "# kglite-visual protocol framing baseline — EXACT.\n\
         #\n\
         # Generated by crates/kglite-visual-core/tests/protocol_baseline.rs.\n\
         # Regenerate with `cargo test -p kglite-visual-core`; \
         `make check-protocol-baseline` fails on drift.\n\
         #\n\
         # Header words are u32 little-endian, in wire order:\n\
         #   version | msg_type | seq | flags | payload_len | payload_offset\n\
         # Every frame is padded with zeros to a multiple of 4 bytes.\n",
    );
    let _ = writeln!(out, "\nprotocol_version {PROTOCOL_VERSION}");
    let _ = writeln!(out, "header_bytes {HEADER_BYTES}");
    let _ = writeln!(out, "chunk_target_bytes {CHUNK_TARGET_BYTES}");

    for (name, frames) in &cases {
        let _ = writeln!(out, "\n[{name}] frames={}", frames.len());
        for frame in frames {
            let words: Vec<u32> = (0..6)
                .map(|w| {
                    let at = w * 4;
                    u32::from_le_bytes([frame[at], frame[at + 1], frame[at + 2], frame[at + 3]])
                })
                .collect();
            let _ = writeln!(
                out,
                "  header version={} type={} seq={} flags={} len={} offset={}",
                words[0], words[1], words[2], words[3], words[4], words[5]
            );
            let hex: String = frame.iter().map(|b| format!("{b:02x}")).collect();
            let _ = writeln!(out, "  bytes  {hex}");
        }
    }

    write_if_changed(
        &Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests")
            .join("baselines")
            .join("framing.golden"),
        &out,
    );
}
