#!/usr/bin/env python3
"""The automatic purge for the tiers that declare a lifetime.

``check_dev_docs.py`` *reports* files past their tier's purge lifetime and
deletes nothing, because deciding whether something is reproducible, and which
tier it belongs in, is a judgement a script must not make. That left a WARN
whose only owner was a human reading it, which is the shape of a bound nobody
enforces (doctrine R4). This is the other half: it deletes, but only inside
tiers that were **declared disposable in advance**, and only past the lifetime
those declarations state.

The split that keeps this safe:

* **The tier table is not duplicated here.** It is imported from
  ``check_dev_docs.py``, which mirrors ``dev-docs/README.md``. A pruner with
  its own copy of the lifetimes is a pruner that eventually disagrees with the
  document promising them.
* **Tier assignment stays a human judgement.** The ``dev-docs-cleanup`` skill
  owns what goes *into* each tier — including which durable thing must be
  rescued out of a disposable one. This only enforces the lifetime of what is
  already there, and it never invents a tier for an unclassified path: a file
  outside a listed disposable tier is left alone, because an age-only sweep
  destroys whatever was placed in the wrong tier (CLAUDE.md → "Dev-environment
  cleanliness").
* **It prints every deletion.** A purge whose output is a count is a purge you
  cannot audit after the fact.

Exit codes: 0 pruned (or nothing to prune), 2 the pruner could not do its job.
"""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from check_dev_docs import PURGE_DAYS, _tier_of  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DEV_DOCS = ROOT / "dev-docs"

#: Playwright writes traces, screenshots and videos for every failing e2e run
#: and an HTML report beside them. Both are regenerated by the next `make e2e`,
#: both are gitignored, and neither had an owner before this file existed —
#: the exact "a path the tooling writes outside git with no bound" shape R4
#: names. A week is long enough to still be reading yesterday's failure.
PLAYWRIGHT_TIERS = {
    Path("frontend/tests/e2e/artifacts"): 7,
    Path("frontend/playwright-report"): 7,
}


def _age_days(path: Path, now: float) -> float:
    return (now - path.stat().st_mtime) / 86400.0


def _prune_tree(root: Path, limit_days: int, label: str, now: float, dry_run: bool) -> tuple[int, int]:
    """Delete files under ``root`` older than ``limit_days``.

    Returns ``(deleted, bytes_freed)``. Directories left empty afterwards are
    removed too, but ``root`` itself always survives — a tier that vanishes
    when it empties reads as a missing tier the next time something looks.
    """
    if not root.is_dir():
        return (0, 0)

    deleted = 0
    freed = 0
    for path in sorted(root.rglob("*"), key=lambda p: len(p.parts), reverse=True):
        if path.is_dir():
            if not any(path.iterdir()) and not dry_run:
                path.rmdir()
            continue
        if not path.is_file() or path.is_symlink():
            continue
        age = _age_days(path, now)
        if age <= limit_days:
            continue
        size = path.stat().st_size
        rel = path.relative_to(ROOT) if path.is_relative_to(ROOT) else path
        print(f"  {'would delete' if dry_run else 'deleted'} {rel}  ({label}, {age:.1f}d old, limit {limit_days}d)")
        if not dry_run:
            path.unlink()
        deleted += 1
        freed += size
    return (deleted, freed)


def prune(dry_run: bool = False, now: float | None = None, root: Path | None = None) -> int:
    now = time.time() if now is None else now
    base = ROOT if root is None else root
    dev_docs = base / "dev-docs"

    deleted = 0
    freed = 0

    # dev-docs' disposable tiers, straight from the shared table. `bench/out`
    # must be tested before `bench`, which is what `_tier_of` already
    # guarantees; iterating the table keeps the two files in step.
    for tier, limit_days in sorted(PURGE_DAYS.items()):
        tier_root = dev_docs / tier
        # Belt and braces: never prune a path whose own tier classification
        # disagrees with the directory it sits in.
        if tier_root.is_dir() and _tier_of(Path(tier)) != tier:
            print(f"prune: could not run — tier '{tier}' does not classify as itself", file=sys.stderr)
            return 2
        d, f = _prune_tree(tier_root, limit_days, f"dev-docs/{tier}", now, dry_run)
        deleted += d
        freed += f

    for rel, limit_days in sorted(PLAYWRIGHT_TIERS.items()):
        d, f = _prune_tree(base / rel, limit_days, str(rel), now, dry_run)
        deleted += d
        freed += f

    verb = "would free" if dry_run else "freed"
    if deleted:
        print(f"prune: {deleted} file(s) past their tier's lifetime, {verb} {freed / (1024 * 1024):.1f} MB")
    else:
        print("prune: nothing past its tier's lifetime")
    return 0


def self_test() -> int:
    """Prove the pruner deletes what it must and keeps what it must (R1).

    A purge that has never been watched taking a file is not a purge, and one
    that has never been watched *sparing* a file is worse — it is a data-loss
    scheduler nobody has read. Four observations, on a throwaway tree.
    """
    failures: list[str] = []
    now = time.time()
    old = now - 40 * 86400
    fresh = now - 1 * 3600

    with tempfile.TemporaryDirectory() as tmp:
        base = Path(tmp)
        out = base / "dev-docs" / "bench" / "out"
        results = base / "dev-docs" / "bench" / "results"
        pw = base / "frontend" / "tests" / "e2e" / "artifacts"
        for d in (out, results, pw):
            d.mkdir(parents=True)

        stale = out / "scale-20000.kgl"
        recent = out / "scale-1000.kgl"
        durable = results / "results.csv"
        stale_trace = pw / "trace.zip"
        for path, mtime in (
            (stale, old),
            (recent, fresh),
            (durable, old),
            (stale_trace, old),
        ):
            path.write_bytes(b"x" * 1024)
            os.utime(path, (mtime, mtime))

        prune(now=now, root=base)

        if stale.exists():
            failures.append("a 40-day file in the disposable bench/out tier survived the purge")
        if not recent.exists():
            failures.append("a 1-hour file in bench/out was purged — the age test is not being read")
        if not durable.exists():
            failures.append("a 40-day file in the DURABLE bench/results tier was purged")
        if stale_trace.exists():
            failures.append("a 40-day Playwright artifact survived the purge")

    if failures:
        print("prune --self-test: FAIL", file=sys.stderr)
        for failure in failures:
            print(f"  {failure}", file=sys.stderr)
        return 1
    print("prune --self-test: OK — 4 observations (2 purged, 2 spared)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true", help="list what would go, delete nothing")
    ap.add_argument(
        "--self-test",
        action="store_true",
        help="prove the purge both deletes and spares on a fixture (R1)",
    )
    args = ap.parse_args()
    if args.self_test:
        return self_test()
    return prune(dry_run=args.dry_run)


if __name__ == "__main__":
    raise SystemExit(main())
